### PR TITLE
added code so its set as button instead of direct login

### PR DESCRIPTION
**Pull request by neeesn**
Sets a button for saml2sso as IDSP so theres option still to use moodle login

### CODE REVIEW

**Comment by neeesn** [comment]
Setting code into dual login - dual login = yes - Button is showed on login - Dual login = no - user is directly redirected to saml login

**Comment by neeesn** [comment]
Option to set url as button in the settings.

**Comment by neeesn** [comment]
Damit -didnt mean to close it

**Comment by mfprimo** [comment]
Hi Daniel, I totally agree with you that the primary purpose of this plugin should be to edirect every user to IdP authentication.

But we have more than 50 Moodle instances and in a few of them we share both SSO and local (or LDAP or DB) user accounts. From our experience, in these cases it is impractical to explain to the users how to login skipping SSO using a query parameter. In addition, I think that the "dual login" term is a little misleading.

Thus my above proposal:
- regardless dual login, saml=off always bypass SSO and prompt the native Moodle auth form: this allow a recovery access mode for administrators and pose no security problem in a well configured system
- with dual login disable, user is always redirect to SSO as in the current plugin release
- with dual login enable, user switch to the native Moodle auth form with the additional button for SSO as in the Henrik's contribute

**Comment by mfprimo** [comment]
Ops...  4cf1590 commit as-is brokes the semantics of dual-login option (see above)

**Comment by dmirandaa** [comment]
Yes, I'll test and change before release e new version, I merged just to resolve the conflicts

**Pull request merged**
